import Link from "next/link";
import SiteLockControl from "@/components/SiteLockControl";
import { getDashboardStats } from "@/lib/site-analytics";

function RankedList({ title, rows, empty }: { title: string; rows: Array<{ label: string; count: number }>; empty: string }) {
  return <section className="border border-[var(--gold-light)] bg-[#fcfaf6] p-6"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[var(--gold)]">Activity</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl text-[var(--navy)]">{title}</h2>{rows.length ? <ol className="mt-5 divide-y divide-[var(--gold-light)]">{rows.map((row, index) => <li className="flex items-center justify-between gap-4 py-3" key={row.label}><span className="min-w-0 truncate text-stone-700"><span className="mr-3 text-xs font-bold text-[var(--gold)]">{index + 1}</span>{row.label}</span><strong className="text-[var(--navy)]">{row.count}</strong></li>)}</ol> : <p className="mt-5 text-sm leading-6 text-stone-600">{empty}</p>}</section>;
}

export default async function AdminPage() {
  const stats = await getDashboardStats();
  const allSearches = stats.topSearches.reduce((total, item) => total + item.count, 0);
  const overview = [
    { label: "Visits today", value: stats.visitsToday, detail: "Fresh activity since midnight UTC." },
    { label: "Searches today", value: stats.searchesToday, detail: "The places visitors are looking for right now." },
    { label: "All recorded visits", value: stats.visits, detail: "One visit per browser session, per page." },
    { label: "All recorded searches", value: allSearches, detail: "Use this to decide what to update next." },
  ];

  return <main className="min-h-screen bg-[var(--cream)]"><header className="border-b border-[var(--gold-light)]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-5 px-5 py-6 sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--gold)]">White Glove Itineraries</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-4xl text-[var(--navy)]">Owner&apos;s dashboard</h1></div><Link href="/" className="border border-[var(--gold)] px-4 py-3 text-xs font-bold uppercase tracking-[0.12em] text-[var(--navy)]">View website</Link></div></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{overview.map((item) => <div key={item.label} className="border border-[var(--gold-light)] bg-[#fcfaf6] p-6"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[var(--gold)]">{item.label}</p><p className="mt-3 font-[family-name:var(--font-display)] text-5xl text-[var(--navy)]">{item.value}</p><p className="mt-3 text-sm leading-6 text-stone-600">{item.detail}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><SiteLockControl initialLocked={stats.siteLocked} configured={stats.configured} /><section className="border border-[var(--gold-light)] bg-[#fcfaf6] p-6"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[var(--gold)]">Data connection</p><p className="mt-2 font-[family-name:var(--font-display)] text-3xl text-[var(--navy)]">{stats.configured ? "Connected" : "Not connected"}</p><p className="mt-3 text-sm leading-6 text-stone-600">{stats.configured ? "Visitor activity and search interest are being saved privately." : "Connect the private analytics store to begin collecting real traffic."}</p></section></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><RankedList title="Most searched places" rows={stats.topSearches} empty="No searches have been recorded yet. Once connected, each completed destination search will appear here." /><RankedList title="Most visited pages" rows={stats.topPages} empty="No page visits have been recorded yet. Once connected, you will see the pages visitors use most." /></div><section className="mt-5 border border-[var(--gold-light)] bg-[#fcfaf6] p-6"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[var(--gold)]">Owner&apos;s use</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl text-[var(--navy)]">Choose the next destination to deepen.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-stone-600">The search list shows what visitors need first. Open the directory to update an exact city, cemetery, or practical section without guessing what matters most.</p><Link href="/stops" className="mt-5 inline-block border border-[var(--gold)] px-4 py-3 text-xs font-bold uppercase tracking-[0.12em] text-[var(--navy)]">Open destination directory</Link></section></section></main>;
}
