import Link from "next/link";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import TravelAssistantBox from "@/components/TravelAssistantBox";
import { pageMetadata } from "@/lib/seo";

/**
 * The travel assistant's own page.
 *
 * IT USED TO LIVE ON THE ITINERARY PAGE, and the hand-off from the corner
 * assistant sent people there — so somebody who asked a question got a trip
 * planner, with their answer above it and a day-by-day builder they had not
 * asked for underneath. The owner's words: "now it goes into the itinerary
 * page. I don't like that."
 *
 * So the conversation gets a page built for a conversation, and the planner
 * goes back to being the planner. Nothing else moved: the box on the home page
 * still answers where it stands, because a question asked there is answered
 * without going anywhere, which was never the complaint.
 *
 * NOT A FIFTH FRONT DOOR. lib/starting-points.ts names the four ways into this
 * site and this is not one of them — it is where an assistant that already
 * exists does its work. It is reached by asking, not by being sold.
 */
export const metadata = pageMetadata({
  title: "Ask the AI travel assistant | White Glove Kosher Travel",
  description:
    "Ask about a destination, a kever, kosher food or what to do somewhere, and get an answer with links to the pages it came from.",
  path: "/assistant",
});

export default async function AssistantPage({
  searchParams,
}: {
  // `ask` carries a question handed over by the site assistant in the corner.
  // Read here on the server so the panel opens already asking it — one render,
  // no flicker, and no difference between what the server drew and what the
  // browser draws.
  searchParams: Promise<{ ask?: string | string[] }>;
}) {
  const asked = await searchParams;
  const initialAsk = (Array.isArray(asked.ask) ? asked.ask[0] : asked.ask ?? "").replace(/\s+/g, " ").trim().slice(0, 500);

  return (
    <main className="min-h-screen bg-[var(--cream)]">
      <Navbar />

      <section className="wg-page-hero border-b border-[var(--gold-light)] px-5 py-12 sm:px-8 sm:py-16">
        <div className="mx-auto max-w-3xl">
          <p className="text-xs font-bold uppercase tracking-[0.24em] text-[var(--gold-ink)]">White Glove</p>
          <h1 className="mt-4 font-[family-name:var(--font-display)] text-4xl leading-tight text-[var(--navy)] sm:text-5xl">
            Ask the AI travel assistant
          </h1>
          <p className="mt-4 text-base leading-7 text-stone-600">
            Ideas for a destination, a kever, kosher food, or what to do somewhere with an afternoon. Answers are
            generated by AI and may not have been checked by White Glove — for our own verified listings, use the{" "}
            <Link href="/kosher" className="font-semibold text-[var(--navy)] underline decoration-[var(--gold)] underline-offset-4">
              kosher food finder
            </Link>{" "}
            or{" "}
            <Link href="/search" className="font-semibold text-[var(--navy)] underline decoration-[var(--gold)] underline-offset-4">
              site search
            </Link>
            .
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-5 py-10 sm:px-8 sm:py-12">
        <TravelAssistantBox initialAsk={initialAsk} labelledOutside />

        <p className="mt-8 text-sm leading-7 text-stone-600">
          Ready to put it into a trip?{" "}
          <Link href="/itinerary" className="font-semibold text-[var(--navy)] underline decoration-[var(--gold)] underline-offset-4">
            Build it in the itinerary planner
          </Link>
          .
        </p>
      </section>

      <Footer />
    </main>
  );
}
