/**
 * What the database currently says, written down where the repository can see
 * it.
 *
 * THE PROBLEM THIS EXISTS FOR, in the owner's words: "I entered a number and
 * you don't see it." He was right, and it was not a one-off. The site's content
 * lives in two places at once — the data/*.ts files, which are in git, and the
 * Postgres database, which is where everything he adds through the admin goes.
 * The public pages merge the two, so the site is correct. Nothing else is. A
 * checkout of this repository shows half the truth, and anybody working from
 * one — a person, or an agent with no database credentials — will state that
 * half confidently and be wrong. A shomer's number he had entered was reported
 * back to him as missing.
 *
 * So the database gets written into the repository, on a schedule, as one file.
 * After that a checkout is the whole picture, the file is versioned so a change
 * to a phone number is a diff somebody can read, and it doubles as the offline
 * copy for the day the database is unreachable.
 *
 * PUBLISHED CONTENT ONLY, and that is a hard rule rather than a default. This
 * repository is public. lib/content-export.ts builds the other file — the
 * private backup, which holds drafts and everything else and is explicitly not
 * for posting anywhere. This one holds what the site already shows to anybody
 * who loads the page it is on: nothing here is a disclosure, because all of it
 * is a page away. Draft pages are dropped. So is anything staged for review but
 * not published.
 */

import type { PrismaClient } from "@prisma/client";

/** Bumped when the shape changes, so a reader knows what it is holding. */
export const SNAPSHOT_SCHEMA_VERSION = 2;

export type SnapshotContact = {
  label: string;
  /** Whose number it is. Absent until the database has the column. */
  name: string | null;
  phone: string | null;
  email: string | null;
  note: string | null;
  lastVerified: string | null;
};

export type SnapshotBurial = {
  name: string;
  yiddishName: string;
  knownAs: string | null;
  seforim: string | null;
  yahrzeit: string | null;
  note: string | null;
};

export type SnapshotCemetery = {
  slug: string;
  city: string;
  yiddishCity: string;
  name: string;
  yiddishName: string;
  country: string;
  address: string | null;
  coordinates: string | null;
  arrivalNotes: string[];
  accessNote: string | null;
  status: string;
  sourceUrl: string | null;
  lastVerified: string | null;
  burials: SnapshotBurial[];
  contacts: SnapshotContact[];
};

export type SnapshotListing = {
  slug: string;
  name: string;
  city: string;
  country: string;
  status: string;
};

export type SnapshotPage = {
  slug: string;
  title: string;
  seoTitle: string;
  seoDescription: string;
  status: string;
};

/**
 * A directory listing the owner typed in, as the public page shows it.
 *
 * ONLY WHAT /directory ALREADY SHOWS. This file is committed to a public
 * repository, so a listing that is not published is not here, and a phone
 * number goes in only when the same consent rule that puts it on the page says
 * it may — publishableContact, the one used by the page itself. The owner's own
 * notes and his record of why something is featured are never here at all.
 *
 * WHY THEY ARE HERE AT ALL. These listings live in one Redis key and had no
 * backup of any kind. The owner lost his to a bug in that store and there was
 * nothing to restore from. The complete copy is the private admin export; this
 * is the automatic one, and it is better than nothing by a wide margin.
 */
export type SnapshotProvider = {
  id: string;
  name: string;
  category: string;
  tagline: string | null;
  description: string | null;
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  website: string | null;
  basedIn: string | null;
  regions: string | null;
  languages: string | null;
  specialties: string | null;
  featured: boolean;
  createdAt: string;
};

export type ContentSnapshot = {
  schemaVersion: number;
  /** ISO, from the caller — nothing here reads the clock itself. */
  takenAt: string;
  about: string;
  counts: Record<string, number>;
  cemeteries: SnapshotCemetery[];
  attractions: SnapshotListing[];
  stays: SnapshotListing[];
  areas: SnapshotListing[];
  pages: SnapshotPage[];
  /**
   * Published directory listings from the Redis store.
   *
   * Empty when the snapshot ran without Upstash credentials — see
   * `directorySource` for which of the two it was, because an empty list and
   * "could not look" must not read the same in a backup.
   */
  directory: SnapshotProvider[];
  directorySource: "store" | "not-configured";
};

const ABOUT =
  "What the White Glove database holds, written into the repository so a checkout shows the same content the live " +
  "site does. Published content only — the same information any visitor can read on the page it belongs to. " +
  "Generated by scripts/write-snapshot.ts; do not edit by hand. The private backup, which includes drafts, is the " +
  "admin export and is a different file. Directory listings here are the ones already shown on /directory, with a " +
  "phone number only where the same consent rule the page uses allows it.";

function iso(value: Date | null | undefined): string | null {
  return value ? value.toISOString() : null;
}

/**
 * Read the whole published corpus.
 *
 * Takes the client rather than importing it, so the script can hand in a plain
 * PrismaClient without dragging the site's request-scoped one into a CLI.
 */
/**
 * The published listings, exactly as the public page shows them.
 *
 * Unavailable is NOT the same as none, and the difference is written into the
 * file. A backup that cannot tell "he has no listings" from "I could not look"
 * is a backup that will one day be restored from confidently and wrongly.
 */
async function snapshotDirectory(): Promise<{ directory: SnapshotProvider[]; directorySource: "store" | "not-configured" }> {
  if (!process.env.UPSTASH_REDIS_REST_URL || !process.env.UPSTASH_REDIS_REST_TOKEN) {
    return { directory: [], directorySource: "not-configured" };
  }
  const { listStoredProviders } = await import("@/lib/directory-store");
  const { publishableContact } = await import("@/lib/provider-contact");
  const stored = await listStoredProviders();
  return {
    directorySource: "store",
    directory: stored
      // Same rule the page uses. An unpublished listing is not public, so it
      // does not belong in a file committed to a public repository.
      .filter((p) => p.published !== false)
      .map((p) => {
        const contact = publishableContact(p, { contactConsent: p.contactConsent });
        return {
          id: p.id,
          name: p.name,
          category: p.category,
          tagline: p.tagline ?? null,
          description: p.description ?? null,
          phone: contact.phone,
          whatsapp: contact.whatsapp,
          email: p.email ?? null,
          website: p.website ?? null,
          basedIn: p.basedIn ?? null,
          regions: p.regions ?? null,
          languages: p.languages ?? null,
          specialties: p.specialties ?? null,
          featured: Boolean(p.featured),
          createdAt: p.createdAt,
        };
      }),
  };
}

export async function buildContentSnapshot(prisma: PrismaClient, takenAt: string): Promise<ContentSnapshot> {
  // The directory listings the owner typed in. They live in Redis, not the
  // database, so this is a separate read and it is allowed to come back
  // unavailable — the scheduled run may have no Upstash credentials, and
  // `directorySource` records which of the two happened.
  const { directory, directorySource } = await snapshotDirectory();

  const [cemeteries, attractions, stays, areas, pages] = await Promise.all([
    prisma.cemetery.findMany({
      include: {
        burials: { orderBy: { name: "asc" } },
        // NAMED COLUMNS, for the reason written above the same select in
        // lib/content.ts: `contacts: true` asks for every column the generated
        // client knows about, so the day one is added to the schema this read
        // starts failing against a database the upgrade has not reached — and
        // a snapshot that fails is a night with no record of what changed.
        contacts: {
          orderBy: { label: "asc" },
          select: { id: true, label: true, phone: true, email: true, note: true, lastVerified: true },
        },
      },
      orderBy: [{ country: "asc" }, { city: "asc" }, { slug: "asc" }],
    }),
    prisma.attraction.findMany({ orderBy: [{ country: "asc" }, { city: "asc" }, { slug: "asc" }] }),
    prisma.kosherStay.findMany({ orderBy: [{ country: "asc" }, { city: "asc" }, { slug: "asc" }] }),
    prisma.kosherArea.findMany({ orderBy: [{ country: "asc" }, { city: "asc" }, { slug: "asc" }] }),
    // The one table with a real draft state. A draft is unfinished copy, and
    // this file goes into a public repository.
    prisma.page.findMany({ where: { status: "PUBLISHED" }, orderBy: { slug: "asc" } }),
  ]);

  // Whose number it is, read on its own and allowed to fail. It is the newest
  // column here, and a snapshot without the names is worth far more than no
  // snapshot at all.
  const names = new Map<string, string | null>();
  try {
    for (const row of await prisma.contact.findMany({ select: { id: true, name: true } })) {
      names.set(row.id, row.name);
    }
  } catch {
    // The column is not there yet. Every name reads as absent, which it is.
  }

  const snapshot: ContentSnapshot = {
    schemaVersion: SNAPSHOT_SCHEMA_VERSION,
    takenAt,
    about: ABOUT,
    counts: {},
    cemeteries: cemeteries.map((row) => ({
      slug: row.slug,
      city: row.city,
      yiddishCity: row.yiddishCity,
      name: row.name,
      yiddishName: row.yiddishName,
      country: row.country,
      address: row.address,
      coordinates: row.coordinates,
      arrivalNotes: row.arrivalNotes,
      accessNote: row.accessNote,
      status: row.status,
      sourceUrl: row.sourceUrl,
      lastVerified: iso(row.lastVerified),
      burials: row.burials.map((burial) => ({
        name: burial.name,
        yiddishName: burial.yiddishName,
        knownAs: burial.knownAs,
        seforim: burial.seforim,
        yahrzeit: burial.yahrzeit,
        note: burial.note,
      })),
      // The shomer numbers. These are printed on the beis hachaim's own page
      // with a "Call" button on them, so they are not a secret being let out —
      // they are the single most perishable thing on this site, and a file that
      // shows when one changed is worth having.
      contacts: row.contacts.map((contact) => ({
        label: contact.label,
        name: names.get(contact.id) ?? null,
        phone: contact.phone,
        email: contact.email,
        note: contact.note,
        lastVerified: iso(contact.lastVerified),
      })),
    })),
    attractions: attractions.map(listing),
    stays: stays.map(listing),
    areas: areas.map(listing),
    pages: pages.map((page) => ({
      slug: page.slug,
      title: page.title,
      seoTitle: page.seoTitle,
      seoDescription: page.seoDescription,
      status: page.status,
    })),
    directory,
    directorySource,
  };

  snapshot.counts = {
    cemeteries: snapshot.cemeteries.length,
    kevarim: snapshot.cemeteries.reduce((sum, c) => sum + c.burials.length, 0),
    contacts: snapshot.cemeteries.reduce((sum, c) => sum + c.contacts.length, 0),
    attractions: snapshot.attractions.length,
    stays: snapshot.stays.length,
    areas: snapshot.areas.length,
    pages: snapshot.pages.length,
    directory: snapshot.directory.length,
  };

  return snapshot;
}

function listing(row: { slug: string; name: string; city: string; country: string; status: string }): SnapshotListing {
  return { slug: row.slug, name: row.name, city: row.city, country: row.country, status: row.status };
}

/**
 * Is this snapshot worth trusting?
 *
 * A snapshot with no cemeteries in it is not a site with no cemeteries — it is
 * a run that reached an empty or wrong database. Committing that would replace
 * a good copy with a false one, and the false one would look authoritative.
 * The writer refuses on this rather than overwriting.
 */
export function snapshotProblem(snapshot: ContentSnapshot): string | null {
  if (snapshot.schemaVersion !== SNAPSHOT_SCHEMA_VERSION) return "Snapshot schema version does not match this code.";
  if (!snapshot.takenAt) return "The snapshot has no timestamp.";
  if (snapshot.cemeteries.length === 0) {
    return "No cemeteries came back. That is an empty or wrong database, not an empty site — refusing to overwrite.";
  }
  return null;
}
