/**
 * Telling a business apart from a piece of the web page it was scraped off.
 *
 * WHY THIS EXISTS. The kosher directories are harvested from certifier and
 * community websites, and a harvester that walks a page's rows sometimes picks
 * up the page's own furniture instead: a "Need Help?" support box, a "Join Our
 * Newsletter" form, a "Latest Tours" sidebar, a cookie notice's "Close"
 * button. Ten of those reached the published directory. The site did not just
 * show them — it wrapped each one in its own generated sentence, so a reader
 * was told "Need Help? is listed as a kosher restaurant by Chabad of
 * Thailand". That is the site asserting a kashrus claim, on a named
 * certifier's authority, about a thing that does not exist.
 *
 * WHERE THE GUARD BELONGS. The import pack already validates hard
 * (data/imports/kosher-food-batch/validate.ts) — structure, dedupe, sources,
 * no kosher-style stand-ins. It has no opinion on whether a NAME is a business,
 * which is why these passed. So the check lives here, in pure data, and is used
 * twice: the pack validator fails loudly on a future harvest, and the public
 * read path filters as a fail-safe. A generated file can be regenerated by
 * someone who never reads the validator; the read path cannot be bypassed.
 *
 * DELIBERATELY CONSERVATIVE. A wrongly-hidden real restaurant is worse than a
 * visible piece of junk, because nobody ever finds out about the first one.
 * "Home Sweet Challah" is a real Montreal bakery and an earlier draft of this
 * caught it on a "home" prefix; "The Milky Way" and "The Upper Crust" are real
 * Los Angeles and Cedarhurst restaurants. So a bare generic word is junk only
 * when it is the WHOLE name, and a multi-word phrase has to be one no business
 * would be called.
 */

/**
 * Single words that are web-page furniture when they stand alone, and an
 * ordinary part of a name when they do not. Matched against the entire name.
 */
const UI_WORD = new Set([
  "close",
  "menu",
  "search",
  "home",
  "share",
  "next",
  "previous",
  "back",
  "subscribe",
  "newsletter",
  "categories",
  "tags",
  "archive",
  "more",
]);

/** Phrases no restaurant, bakery or grocery is called. Matched as a prefix. */
const UI_PHRASE =
  /^(need help|join our newsletter|latest tours|latest news|read more|learn more|click here|contact us|about us|view all|see all|sign up|log ?in|back to top|follow us|skip to content|toggle navigation|privacy policy|terms of|cookie)/i;

/** A name carrying markup or script is not a name at all. */
const CODE = /[<>{}]|\|\||=>|function\s*\(|window\.|document\.|src=|href=|height=|width=/;

/** A sentence caught mid-flow, where a business name should be. */
const SENTENCE = /^(please allow|please note|we will|we are|you can|you may|up to|click )/i;

function bare(value: string): string {
  return value.trim().replace(/[?!.:,\s]+$/, "").toLowerCase();
}

/**
 * Why this is not a business at all, or null when it looks like one.
 *
 * The reason is for the admin and the build log — never for a customer, who
 * simply does not see the record. AGENTS.md: internal content status is not
 * customer-facing language.
 */
export function notABusinessReason(name: string): string | null {
  const trimmed = name.trim();
  if (trimmed.length < 3) return "the name is too short to be a business";
  if (CODE.test(trimmed)) return "the name contains page markup or script";
  if (UI_WORD.has(bare(trimmed))) return `"${trimmed}" on its own is a page control, not a business`;
  if (UI_PHRASE.test(trimmed)) return `"${trimmed}" is website furniture, not a business`;
  if (SENTENCE.test(trimmed)) return `"${trimmed}" is a sentence caught mid-flow, not a name`;
  return null;
}

/**
 * The HTML entities a scraped name arrives carrying. A customer was being
 * shown "IGA Cote St Luc &#8211; Kosher Counters" literally, dash and all.
 * Only the handful that actually appear in this data — there is no reason to
 * carry a full entity table for six characters.
 */
const ENTITIES: Array<[RegExp, string]> = [
  [/&#8211;/g, "–"],
  [/&#8212;/g, "—"],
  [/&#8216;|&#8217;|&rsquo;|&lsquo;/g, "’"],
  [/&#8220;|&#8221;|&rdquo;|&ldquo;/g, "”"],
  [/&#038;|&amp;/g, "&"],
  [/&quot;/g, '"'],
  [/&nbsp;/g, " "],
];

/** A scraped name as it should have been stored. Never changes a clean one. */
export function cleanListingName(name: string): string {
  let out = name;
  for (const [pattern, replacement] of ENTITIES) out = out.replace(pattern, replacement);
  return out.replace(/\s+/g, " ").trim();
}

/**
 * Keep only what is a real business, with its name tidied.
 *
 * Generic over anything carrying a name, so the kosher directory and any later
 * scraped set can share one door.
 */
export function withoutScrapedJunk<T extends { name: string }>(rows: readonly T[]): T[] {
  const kept: T[] = [];
  for (const row of rows) {
    if (notABusinessReason(row.name)) continue;
    const name = cleanListingName(row.name);
    kept.push(name === row.name ? row : { ...row, name });
  }
  return kept;
}
