/**
 * Telling a business apart from a piece of the web page it was scraped off.
 *
 * WHY THIS EXISTS. The kosher directories are harvested from certifier and
 * community websites, and a harvester that walks a page's rows sometimes picks
 * up the page's own furniture instead: a "Need Help?" support box, a "Join Our
 * Newsletter" form, a "Latest Tours" sidebar, a cookie notice's "Close"
 * button. Ten of those reached the published directory. The site did not just
 * show them — it wrapped each one in its own generated sentence, so a reader
 * was told "Need Help? is listed as a kosher restaurant by Chabad of
 * Thailand". That is the site asserting a kashrus claim, on a named
 * certifier's authority, about a thing that does not exist.
 *
 * WHERE THE GUARD BELONGS. The import pack already validates hard
 * (data/imports/kosher-food-batch/validate.ts) — structure, dedupe, sources,
 * no kosher-style stand-ins. It has no opinion on whether a NAME is a business,
 * which is why these passed. So the check lives here, in pure data, and is used
 * twice: the pack validator fails loudly on a future harvest, and the public
 * read path filters as a fail-safe. A generated file can be regenerated by
 * someone who never reads the validator; the read path cannot be bypassed.
 *
 * DELIBERATELY CONSERVATIVE. A wrongly-hidden real restaurant is worse than a
 * visible piece of junk, because nobody ever finds out about the first one.
 * "Home Sweet Challah" is a real Montreal bakery and an earlier draft of this
 * caught it on a "home" prefix; "The Milky Way" and "The Upper Crust" are real
 * Los Angeles and Cedarhurst restaurants. So a bare generic word is junk only
 * when it is the WHOLE name, and a multi-word phrase has to be one no business
 * would be called.
 */

/**
 * Single words that are web-page furniture when they stand alone, and an
 * ordinary part of a name when they do not. Matched against the entire name.
 */
const UI_WORD = new Set([
  "close",
  "menu",
  "search",
  "home",
  "share",
  "next",
  "previous",
  "back",
  "subscribe",
  "newsletter",
  "categories",
  "tags",
  "archive",
  "more",
]);

/**
 * Phrases no restaurant, bakery or grocery is called. Matched as a prefix, but
 * only where the phrase ENDS on a word boundary — the trailing (?![a-z]) is
 * not decoration. Without it "cookie" swallowed "Cookielada", a real bakery,
 * the day it was added to the directory. A prefix rule with no boundary is a
 * rule that eats a longer word starting with the same letters.
 *
 * And a cookie banner is never called just "Cookie" — it is "Cookie policy",
 * "Cookie notice", "Cookie settings". So the entry names those outright,
 * because "Cookie Corner" is a bakery and this filter must not decide
 * otherwise.
 */
const UI_PHRASE =
  /^(need help|join our newsletter|latest tours|latest news|read more|learn more|click here|contact us|about us|view all|see all|sign up|log ?in|back to top|follow us|skip to content|toggle navigation|privacy policy|terms of|cookie (?:policy|notice|settings|preferences|consent))(?![a-z])/i;

/** A name carrying markup or script is not a name at all. */
const CODE = /[<>{}]|\|\||=>|function\s*\(|window\.|document\.|src=|href=|height=|width=/;

/** A sentence caught mid-flow, where a business name should be. */
const SENTENCE = /^(please allow|please note|we will|we are|you can|you may|up to|click )/i;

function bare(value: string): string {
  return value.trim().replace(/[?!.:,\s]+$/, "").toLowerCase();
}

/**
 * Why this is not a business at all, or null when it looks like one.
 *
 * The reason is for the admin and the build log — never for a customer, who
 * simply does not see the record. AGENTS.md: internal content status is not
 * customer-facing language.
 */
export function notABusinessReason(name: string): string | null {
  const trimmed = name.trim();
  if (trimmed.length < 3) return "the name is too short to be a business";
  if (CODE.test(trimmed)) return "the name contains page markup or script";
  if (UI_WORD.has(bare(trimmed))) return `"${trimmed}" on its own is a page control, not a business`;
  if (UI_PHRASE.test(trimmed)) return `"${trimmed}" is website furniture, not a business`;
  if (SENTENCE.test(trimmed)) return `"${trimmed}" is a sentence caught mid-flow, not a name`;
  return null;
}

/**
 * The HTML entities a scraped name arrives carrying. A customer was being
 * shown "IGA Cote St Luc &#8211; Kosher Counters" literally, dash and all.
 * Only the handful that actually appear in this data — there is no reason to
 * carry a full entity table for six characters.
 */
const ENTITIES: Array<[RegExp, string]> = [
  [/&#8211;/g, "–"],
  [/&#8212;/g, "—"],
  [/&#8216;|&#8217;|&rsquo;|&lsquo;/g, "’"],
  [/&#8220;|&#8221;|&rdquo;|&ldquo;/g, "”"],
  [/&#038;|&amp;/g, "&"],
  [/&quot;/g, '"'],
  [/&nbsp;/g, " "],
];

/**
 * The labels a scraped block runs on into. A harvester that took a listing's
 * whole text node keeps going past the address and swallows the opening hours,
 * the website and the blurb with it — so a customer reads
 * "9806 Hillcroft Ave. Houston, TX 77096 Hours: Sunday-Thursday 11am-8pm…" as
 * though it were one address. Everything from the first label onward belongs
 * to a field this record does not have.
 */
const RUN_ON_LABEL = /\s+(?:Website|Hours|Tel|Telephone|Phone|Fax|Email|E-mail|Address|Open|Kashrut|Kashrus|Supervision)\s*:/i;

/** A scraped name as it should have been stored. Never changes a clean one. */
export function cleanListingName(name: string): string {
  let out = name;
  for (const [pattern, replacement] of ENTITIES) out = out.replace(pattern, replacement);
  // One harvested name ran on into its own labels: "Dino's Mediterranean
  // Cuisine Phone: 832-667-8592 Address:".
  out = out.split(RUN_ON_LABEL)[0] ?? out;
  return out.replace(/\s+/g, " ").trim();
}

/**
 * A scraped address with the rest of the page cut off it, or "" when what is
 * left is not an address at all.
 *
 * BLANK RATHER THAN WRONG. One record's address begins "0823 Website: …" — the
 * tail of a phone number the harvester started mid-way through. Cutting at the
 * label leaves "0823", which is worse than nothing: a reader would try to
 * navigate by it. KosherEatery.address is optional and every renderer guards
 * on it, so an absent address simply does not draw, and the listing keeps its
 * name, its city and its source.
 */
export function trimScrapedAddress(address: string): string {
  const cut = address.split(RUN_ON_LABEL)[0] ?? address;
  const tidy = cut.replace(/\s+/g, " ").replace(/[,\s]+$/, "").trim();
  // A street address has words in it. Digits alone are a fragment of something.
  if (tidy.length < 6 || !/[a-z]/i.test(tidy)) return "";
  return tidy;
}


/**
 * A phone number sitting where the street should be.
 *
 * Five harvested listings carry an address of "020 3667 1200, United Kingdom"
 * — the source published a number and no street, and the harvester put what it
 * found into the address field. A customer reading that gets neither: it is
 * not somewhere to navigate to, and it is not a number they can press.
 *
 * The number is real and worth keeping, and KosherEatery already has a `phone`
 * field with a Call button behind it, so this is a MOVE rather than a
 * deletion. Whatever follows the number is a country or a city, which the
 * listing already carries in its own fields, so nothing is lost by dropping
 * the remainder with it.
 *
 * DELIBERATELY NARROW. The test is that everything before the first comma is
 * digits and phone punctuation with no letters at all — because a US street
 * address begins with a house number, and a looser rule flagged 199 perfectly
 * good ones like "1666 79th Street Causeway, Suite 102". Five is the real
 * count.
 */
export function phoneInAddress(address: string | null | undefined): string | null {
  const first = (address ?? "").split(",")[0].trim();
  if (!first || /[a-z]/i.test(first)) return null;
  if (!/^[+\d][\d\s\-().+]*$/.test(first)) return null;
  const digits = (first.match(/\d/g) ?? []).length;
  // Seven is a local number. Fewer than that is a house number or a postcode.
  if (digits < 7) return null;
  return first;
}

/**
 * Keep only what is a real business, with its name tidied.
 *
 * Generic over anything carrying a name, so the kosher directory and any later
 * scraped set can share one door.
 */
export function withoutScrapedJunk<T extends { name: string; address?: string; phone?: string }>(
  rows: readonly T[],
): T[] {
  const kept: T[] = [];
  for (const row of rows) {
    if (notABusinessReason(row.name)) continue;
    const name = cleanListingName(row.name);

    // A phone number in the address field becomes a phone number. Never
    // overwrites one the listing already has — the address is the doubtful
    // copy, not the authority.
    const strandedPhone = row.phone ? null : phoneInAddress(row.address);
    const address = strandedPhone
      ? undefined
      : row.address === undefined
        ? undefined
        : trimScrapedAddress(row.address) || undefined;

    if (name === row.name && address === row.address && !strandedPhone) {
      kept.push(row);
      continue;
    }
    kept.push({
      ...row,
      name,
      ...(row.address === undefined && !strandedPhone ? {} : { address }),
      ...(strandedPhone ? { phone: strandedPhone } : {}),
    });
  }
  return kept;
}
